[workspace]
members = ["src-tauri", "platx/platx-core", "platx/platx-cli"]
[workspace.dependencies]
anyhow = "1.0.86"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
tar = "0.4.41"
flate2 = "1.0.31"
