[package]
name = "daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
anyhow.workspace = true
tokio.workspace = true
reqwest.workspace = true
models = { path = "../models" }
base64 = "0.22.1"
ring = "0.17.8"
axum = "0.7.5"
url = "2.5.2"
