[package]
name = "daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
anyhow.workspace = true
tokio.workspace = true
plugin.path = "../plugin"
base64 = "0.22.1"
axum = { version = "0.7.5", features = ["multipart", "ws"] }
url = "2.5.2"
futures = "0.3.30"
tower-http = { version = "0.5.2", features = ["fs"] }
ed25519-dalek = { version = "2.1.1", features = ["rand_core"] }
rand = "0.8.5"
sha3 = "0.10.8"
urlencoding = "2.1.3"
tokio-util = "0.7.12"
bundler.path = "../bundler"
