[package]
name = "platx-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
clap = { version = "4.5.16", features = ["derive"] }
platx-core = { path = "../platx-core" }
tokio = { workspace = true }
