[package]
name = "bundler"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
flate2.workspace = true
serde.workspace = true
serde_json.workspace = true
tar.workspace = true
urlencoding = "2.1.3"
models.path = "../models"
